### ISSUE TITLE
Usability Suggestions/Feedback

### ISSUE THREAD

**Issue by Asinin3** [Guerra24/LRReader#18]
Time for another list of usability suggestions 🚀 Ordered in importance

**Suggestions**
- [x] New keybinds (similar to LRR's web interface) "R" for Random archive, "F" for Fullscreen Shift+R or F5 for refresh
- [x] If possible, add button (with keybind) to navigate to the next archive in the index you opened it from (so if you opened a gallery from a category go to next archive there, or if you opened one from a search, go to next gallery under the search results).
- [x] If the above is implemented, add option to automatically open next gallery in your index upon reaching the last page of an archive and trying to proceed to the next page. (E.g pushing space at the bottom of the last page, or the right arrow key)
- [x] Make source tags with a url clickable and open a web-browser
- [x] Add prompt or automatically restart the application when a user changes the application theme (it's not obvious you need to)
- [x] ctrl+click on a archive opens in a new tab without switching to it (same as web browsers)

**Feedback:**
Having tabs be opened for settings, tools, bookmarks, takes up a lot of space in the tab-bar quickly and isn't all that useful as you never need multiple of these tabs open. It would save a lot of space if it just went to the Bookmark/Settings/Tools pages when you clicked on the icon, without making a new tab. Similarly, the categories button could do the same, and not open a new tab when you click on categories. And only open a new tab when you open a category. (If possible, only open new tab if a tab for that category isn't already open. Otherwise switch to the tab that is open).

The hover location/overlay size for archive tags is awkward. It would also be really nice if you could click the tags from within the hover. Not sure if there's an elegant way to improve it though. 

Great work on the application by the way!

**Comment by Guerra24** [comment]
- Keybinds: Sure. F5 is already used in, I think, all pages that have some sort of refresh.
- Next gallery navigation: Sure, it would require some work when handling bookmarks but looks doable.
- Clickable source tags: Sure.
- Auto-restart on theme change: Sure.
- Ctrl+click: Since I'm fixing the broken search tabs 😅 this is going to be added there.

**Comment by Guerra24** [comment]
Now the feedback part.

I will probably need to do a bit of research since hiding specific tabs from the tab bar might not be possible.

> If possible, only open new tab if a tab for that category isn't already open. Otherwise switch to the tab that is opened.

That is already implemented. If it is failing for you then that might be a bug but in my tests it works fine.

---
The tags overlay is something I've never been happy with, I don't know how to improve it... I can make it work like the web version where it shows to the side and you can click on it but aside from that I don't know.

**Comment by Guerra24** [comment]
Dynamic theme change is now possible due to a side effect of another change.

![2021-09-01_00-11-42](https://user-images.githubusercontent.com/9023392/131621122-04d88200-b53a-4d79-8cd1-d688c55b8e83.gif)

**Comment by Asinin3** [comment]
Nice!

**Comment by Guerra24** [comment]
It's a bit trickier than I thought. This is a proof of concept so no UI, animations or anything else.

![2021-09-06_13-12-29](https://user-images.githubusercontent.com/9023392/132255073-2b420df5-1323-4c25-ab92-6b0c00a5c11b.gif)

**Comment by Guerra24** [comment]
Okay, everything but the new keybinds was added just as requested.

I decided against adding them because not only it would be a pain adding them everywhere but more importantly it would cause issues with text boxes. This is something I cannot fix and the available workarounds are not 100% reliable.

The only keybind added was F for fullscreen and F5 for refresh was already there.

---
The tabs... unfortunately hiding tabs is not possible without remaking the entire control from scratch.

I was not able to work on the tags overlay for this update, I will revisit this later but meanwhile it will remain the same.

I would suggest giving nightly a try and let me know if something is wrong or needs a change, 1.7.0 is going to release either today or tomorrow.

**Comment by Asinin3** [comment]
Would random archive keybind just from inside a gallery be possible? I find it super useful on the web-browser and spam it until i find something interesting.

**Comment by Guerra24** [comment]
🤔 That is possible, although it would pick any archive. It can make it so it checks for new archives if ctrl or shift is held when pressing the button or key, and don't repeat previously opened archives.

If you're fine with that then I can add it.

**Comment by Asinin3** [comment]
Thanks a lot Guerra <3 great to see how far LRReader has come
