### ISSUE TITLE
Navigating to next page will decrease the total page number

### ISSUE THREAD

**Issue by Slasar41** [Guerra24/LRReader#20]
When I'm trying to go to next page using the next button or selecting from the dropdown menu, the total page number will decrease.

**Comment by Guerra24** [comment]
Because is not a bug but the shitty mirror ffs.

This is how a REAL instance works.
![2021-10-07_16-44-28](https://user-images.githubusercontent.com/9023392/136472327-1fd20c83-0f63-487f-bc10-b0512f018e89.gif)

And this is the shitty mirror.
![2021-10-07_16-44-54](https://user-images.githubusercontent.com/9023392/136472368-a04578d5-3590-4cfb-80f9-d4ddc5c20f1a.gif)

Man I'm gonna end up blocking it because it causes more problems for me than anyone else. I wrote this and made it available for free and this is what I get back, absolute hell.
