### ISSUE TITLE
Longstrip scrolling and WS movement

### ISSUE THREAD

**Issue by hollywings** [Guerra24/LRReader#23]
I love the reader but I would like to see 2 features added, for convenience of course. Can you add a long strip format where you can scroll down and see pages stacked vertically without abruptly snapping to the next page? Also I would love to use W and S for up and down scrolling for situations where I cannot use my right hand. Also, a continuous scrolling mode where if you hold down W/S or Up/Down it will keep scrolling. Thank you very much.

**Comment by Guerra24** [comment]
Hello. Now WASD also work for movement and made holding down arrow up/down or W/S keep scrolling the page.

I'll look into the continuous mode but looks doable.

**Comment by Guerra24** [comment]
Alright gave it a shot and this is the result.

https://user-images.githubusercontent.com/9023392/146498780-26e4a3d3-a628-4af3-b93d-162f6ab20b5d.mp4

And those are the issues.
- Can crash the app (not joking).
- Jump to page doesn't work the first time the reader opens.
- There is no zoom scaling based on window size.
- Scrollbar is broken.
- Scaling filter can break sometimes.
- Reloading resets the reader.
- Changing zoom on any page other than first one will make it jump through the whole thing.
- It can get stuck in the last page.

I have two options for fixing most of those issues.
1. Lock the pages size to some *standard* value.
2. Get rid of all optimizations and load all pages at once (which can be quite heavy with high res archives).

Thoughts on this? otherwise I will go with option 2.
(Yes, I can make it so you can choose one of those options but I would like to avoid this)


I also posted the same in LANraragi's Discord.

**Comment by hollywings** [comment]
Looks to me like option #2 is a reasonable tradeoff, let's see if it works out ok

**Comment by Guerra24** [comment]
Alright I think that's it. Went with a hybrid approach instead.

It will pull all pages and calculate the size of the largest one and then force scale any smaller pages.

The final implementation of the vertical reader is available in nightly if you want to give it a try. I'll close this once v1.7.4 is out.

**Comment by Guerra24** [comment]
v1.7.4 is now out with those changes!
