### ISSUE TITLE
Webp extensions link missing from reader settings

### ISSUE THREAD

**Issue by khakimfc** [Guerra24/LRReader#34]
but it works on thumbnail page

**Comment by Guerra24** [comment]
Hi, could you please provide more information? OS edition, build and LRReader version.

**Comment by Guerra24** [comment]
So turns out Windows 10 LTSC 2019 does not include Webp support. You can add it by installing the following extension: [https://www.microsoft.com/store/productId/9PG2DK419DRG](https://www.microsoft.com/store/productId/9PG2DK419DRG)

I will add a link in the reader settings, so you can install them through there.

**Comment by khakimfc** [comment]
> So turns out Windows 10 LTSC 2019 does not include Webp support. You can add it by installing the following extension: https://www.microsoft.com/store/productId/9PG2DK419DRG
> 
> I will add a link in the reader settings, so you can install them through there.

That is great, thank you.  It seems google webp codec will not work with microsoft apps.

**Comment by Guerra24** [comment]
v1.8.2 is now out with this change!
