### ISSUE TITLE
Features and navigation improvements for LRR

### ISSUE THREAD

**Issue by Pazu5512** [Guerra24/LRReader#9]
Hi again,

Thanks for updating LRReader to match the V0.7 of LANraragi. I haven't had the time to try out the new LRR that much, but so far it seems to run even better than before. I haven't experienced (yet?) the few crashes I could encounter on the previous versions. And thanks again for implementing the #8 suggestions. After a few days of LRReader use, I have a few other ones to suggest, mostly for navigation.

Keep in mind they are suggestions based my own personal use, it may not apply to everyone. For example, I tend to prefer using the mouse for everything when it comes to navigation, but other people are more into keyboard. Though, I think they're universal enough to improve LRR for all. Feel free to discard some if you feel they shouldn't be implemented, or too hard to do, or not worth the development time.

- I feel dumb for not suggesting this in #8, but in the same way you implemented the "Scroll to go next page", I'd suggest to add its mirror feature, aka "Scroll Up to go back to the previous page" (would also applies to Arrow Up for the keyboard). That way it's consistent for going back or forward. I didn't think of suggesting it in #8 because I rarely go back, but sometimes, you're about to blow your loa... herm, you end up on a page you just don't care about, and just want to quickly go back the same way you arrived on that page. Arrow <- and Mouse Backward button work well enough, so it's not a vital feature, but since you already did it for Scroll Down, might as well go all the way and do it for Scroll Up, for consistency.

- Not vital as well, but will be nice for some users : adding a Dark Mode/Light Mode toggle. When you're using Windows in Light Mode, the UWP application stays in Light Mode. When Windows is in Dark Mode, the application is in Dark Mode. This toggle isn't anything fancy, it should just switch/force the Light or Dark Mode for LRR, regardless of your Windows setting. I think UWP applications allow for a native call for Dark/Light mode, so it shouldn't be too hard to implement, but I might be wrong.

- I would add a page count somewhere in the reader, when you're reading an archive. Just a simple "xxx/yyy" (current page/total Nb of pages). Not sure where to put it, maybe on the tab of the opened archive, but it may take up to 7 characters. Otherwise, on some corner of the reader ? As for my own personal use it's fine as I don't browse the pages in full width, so there's plenty of space left on the side corners, but it might get in the way for people looking at their pages in full width. On the tab it's universal enough, I guess. Maybe try a few solutions and see what you feel is the best.

- [EDIT: I just noticed Asinin3 already suggested this in #6] When you're browsing archives on the main page (or after a search), I would add a "Mouse Middle Click/Wheel Click" on a thumbnail to directly open an archive in a new tab (while the focus stays on the main page/search results page). That way you don't have to right click on the thumbnail and then select "open in a new tab" : you gain one click. Basically, it would work the same way as in Firefox/Chrome/etc, where middle clicking a link will open it in a new tab while staying on the current page. It allows for the user (or at least, me :) ) to quickly open archive as you browse, to check them a bit later. Also helps when you have multiple versions of the same archive (translated, untranslated, incomplete, etc), to open them in one go and compare them effortlessly.

- Still on the main archive page / search results page, I would add a "Mouse Forward Button" and "Mouse Backward Button" feature so you can go forward or backward between the results page. Not vital as well, but it allows you to go backward or forward effortlessly when you're browsing a lot of results, without going back up or down the page to click on the dedicated buttons. Also, as not everyone has a mouse with Forward/Backward buttons, maybe implement the equivalent for keyboard users with Arrow Left and Arrow Right.

- It's really personal here, but I think other people might have the same use case as me : on some regular image viewer, CTRL+Scroll Wheel Up allows for zooming in / CTRL+Scroll Wheel Down allows for zooming out the page you're reading, with good adjustment precision thanks to the mouse wheel (though there's a sweet spot to find, padding must not be too high, but not too low or you just end up scrolling kilometers just for a few % of Zoom adjustment). I know you already implemented a little Zoom shortcut, so it's not vital, and it's working well enough. It would just be yet another shortcut.

- Also personal here : I'm not fond of the blur in the Bookmarks page. You don't really get to see the covers as it's too strong, and, well, it's a blur. I would just present the bookmarks the exact same way you already did in the main archive/search results page. Maybe by playing with colors, or cover borders, or adding a little fancy star on the corner of the covers to remind us we're on the bookmarks page, or anything else, if you judge the bookmarks page should be made distinct from the archive/search results page. It's just that the blur is too strong, and disserve the bookmarks browsing. But feel free to let the bookmarks page stay as is if you prefer it that way, as I said, it's purely personal taste, and it already does what's it's supposed to do : listing the bookmarks.

- Probably too complicated, and maybe even downright impossible for UWP applications (?) : a full fledged "Full Screen" mode, that would be activated either by middle clicking anywhere on the page you're reading, and/or by a keyboard shortcut (usually F11 on web browsers), and quitting that fullscreen mode the same way. Page Zooming would stay the same when entering fullscreen, but would be controlled by the shortcut mentioned in a previous bullet point (CTRL+Mouse Wheel). The application is *almost* fullscreen already, but there's still that Windows' window title bar (+the tabs) preventing the reader from reaching true fullscreen mode. I'm not sure if it's possible for an UWP application to either enter in fullscreen with the shortcuts mentioned earlier, or for UWP application automatically hide/show their title bar on mouseOut/mouseOver. And if it's possible, it may be too hard to implement.

That's pretty much it for now, some other ideas might come as I use your cool LRR more. There might be some ideas already popping up (sorting features such as sorting the search results by artists, or grouping results by artists), but they might get out of the scope of what you actually have in mind for your Reader. Again, thanks for reading.

**Comment by Guerra24** [comment]
Ty for the suggestions.

- Actually scroll up to go back *was* going to be implemented but if you scroll back you might expect the view to be at the bottom, this is where I had issues. Damn scroll viewer ffs, it doesn't like to behave sadly (that's why the reader page got rewritten 3 times). I decided to not implement that due to how unreliable it was. If you are fine with going back to the top of the page then I can add it.

- Light/Dark theme switching is something I've look in the past, I can add it but you will need to restart the app, changing the theme without restart is a bit more tricky.

- Yeah sure, status in tab and probably top-left in the reader without background like the close button.

- Middle click to open is also tricky, the view used for the list only supports left-click. I can try by handling that directly in the item so gonna test it first.

- Yeah sure, mouse and keyboard page navigation for the list.

- This is problematic, my scroll wheel is quite unreliable and I can't go get a new one. I can try tho but can't guarantee it will be just right, worst case I can set one % to one scroll step.

- The idea of the blur and the current design is that if you go to the bookmarks you know the deal, there is not much reason to see the cover. Title in bold and count. Also not really visible but the cover has a parallax effect, when there are a lot of bookmarks scrolling will shift the cover a bit.

    Said that I can add a setting to toggle between compact bookmarks (current design) and full size(?) ones (same as list).

- UWP's full screen is true full screen. Hiding the tabs is another thing, the control doesn't support such operation sadly so hiding would be more a hack. I do get an event for titlebar hide/show so that's not a problem.

Opening #10 for search sort by.

I won't be able to work on this until Saturday night or Monday next week as I'm near closing this semester of Uni and I have a lot to do.

**Comment by Pazu5512** [comment]
Oh, don't worry, no need to be hasty. Take your time. Exams are far more important, and take precedence!

**Comment by Guerra24** [comment]
All changes now available in v1.4.1.0
